<template>
  <v-app>
    <v-navigation-drawer
      app
      floating
      permanent
      touchless
      :mini-variant="$vuetify.breakpoint.xsOnly"
    >
      <template #prepend>
        <v-list two-line >
          <v-list-item>
            <v-img
              contain
              height="24"
              :src="$vuetify.theme.dark ? require('../assets/Dorothy.dark.svg') : require('../assets/Dorothy.svg')"
            >
            </v-img>
          </v-list-item>
          <v-list-item>
          </v-list-item>
          <v-list-item>
          </v-list-item>
          <form>
            <v-list-item>
              <v-text-field
                v-model="name"
                label="계정이름"
                required
                outlined
              ></v-text-field>
            </v-list-item>
            <v-list-item>
              <v-text-field
                v-model="password"
                label="비밀번호"
                required
                outlined
              ></v-text-field>
            </v-list-item>
          </form>
        </v-list>
      </template>
    </v-navigation-drawer>
    <router-view></router-view>
  </v-app>
</template>
